#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TranslateHelper.Droid.Resource", IsApplication=true)]

namespace TranslateHelper.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Droid.Core.Resource.String.ApplicationName = global::TranslateHelper.Droid.Resource.String.ApplicationName;
			global::Droid.Core.Resource.String.Hello = global::TranslateHelper.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000b
			public const int ab_white = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int background_header = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int background_light = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int background_white = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int black = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int blue = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int blue100 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int blue50 = 2131099667;
			
			// aapt resource value: 0x7f06000d
			public const int blue_background = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int button_background = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button_background_pressed = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int button_background_selected = 2131099653;
			
			// aapt resource value: 0x7f060014
			public const int grey = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int lightgrey = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int red_background = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int text_black = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int text_light = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int text_normal = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int text_white = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int transparent = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int white = 2131099669;
			
			// aapt resource value: 0x7f06000a
			public const int white1 = 2131099658;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EngRus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FavoritesItemSelector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int RusEng = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SplashScreen = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int TestScreenButtonSelector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int v1favorites = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int v1star10 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int v1star100 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int v1star20 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int v1star50 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int v1starttest = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int v43cleartext = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int v4addtofavorites = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int v4alreadyaddedtofav = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int v4change = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int v4search = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int v5change = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08003b
			public const int FavoritesStatePic = 2131230779;
			
			// aapt resource value: 0x7f080039
			public const int IndexTextView = 2131230777;
			
			// aapt resource value: 0x7f080037
			public const int OriginalTextTextView = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int OriginalTextTranscriptionTextView = 2131230776;
			
			// aapt resource value: 0x7f080026
			public const int PosTextView = 2131230758;
			
			// aapt resource value: 0x7f080024
			public const int SourceTextView = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int TranscriptionTextView = 2131230757;
			
			// aapt resource value: 0x7f08003a
			public const int TranslatedTextTextView = 2131230778;
			
			// aapt resource value: 0x7f080027
			public const int TranslatedTextView = 2131230759;
			
			// aapt resource value: 0x7f08001e
			public const int buttonNew = 2131230750;
			
			// aapt resource value: 0x7f08002b
			public const int buttonSelect100Words = 2131230763;
			
			// aapt resource value: 0x7f080028
			public const int buttonSelect10Words = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int buttonSelect20Words = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int buttonSelect50Words = 2131230762;
			
			// aapt resource value: 0x7f08002e
			public const int buttonSubmitTest1 = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int buttonSubmitTest2 = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int buttonSubmitTest3 = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int buttonSubmitTest4 = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int buttonSubmitTest5 = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int buttonSubmitTest6 = 2131230771;
			
			// aapt resource value: 0x7f080034
			public const int buttonSubmitTest7 = 2131230772;
			
			// aapt resource value: 0x7f080035
			public const int buttonSubmitTest8 = 2131230773;
			
			// aapt resource value: 0x7f08001f
			public const int buttonTranslateBottom = 2131230751;
			
			// aapt resource value: 0x7f08001b
			public const int buttonTranslateTop = 2131230747;
			
			// aapt resource value: 0x7f08000d
			public const int button_add_response = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int button_attachment = 2131230728;
			
			// aapt resource value: 0x7f080012
			public const int button_login = 2131230738;
			
			// aapt resource value: 0x7f08000e
			public const int button_refresh = 2131230734;
			
			// aapt resource value: 0x7f080009
			public const int button_send = 2131230729;
			
			// aapt resource value: 0x7f080016
			public const int button_update = 2131230742;
			
			// aapt resource value: 0x7f080036
			public const int checkResultText = 2131230774;
			
			// aapt resource value: 0x7f08001d
			public const int controlButtons = 2131230749;
			
			// aapt resource value: 0x7f080018
			public const int dictList = 2131230744;
			
			// aapt resource value: 0x7f080020
			public const int favoritesLayout = 2131230752;
			
			// aapt resource value: 0x7f080004
			public const int input_email = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int input_message = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int input_name = 2131230723;
			
			// aapt resource value: 0x7f080011
			public const int input_password = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int input_subject = 2131230725;
			
			// aapt resource value: 0x7f08003c
			public const int label_author = 2131230780;
			
			// aapt resource value: 0x7f08003d
			public const int label_date = 2131230781;
			
			// aapt resource value: 0x7f08000b
			public const int label_last_updated = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int label_message = 2131230720;
			
			// aapt resource value: 0x7f08003e
			public const int label_text = 2131230782;
			
			// aapt resource value: 0x7f080014
			public const int label_title = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int label_version = 2131230741;
			
			// aapt resource value: 0x7f080021
			public const int listFavoritesListView = 2131230753;
			
			// aapt resource value: 0x7f080019
			public const int listInputString = 2131230745;
			
			// aapt resource value: 0x7f08003f
			public const int list_attachments = 2131230783;
			
			// aapt resource value: 0x7f08000f
			public const int list_feedback_messages = 2131230735;
			
			// aapt resource value: 0x7f080022
			public const int list_header_title = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int mainList = 2131230755;
			
			// aapt resource value: 0x7f080041
			public const int menu_dest_selector = 2131230785;
			
			// aapt resource value: 0x7f080040
			public const int menu_dict = 2131230784;
			
			// aapt resource value: 0x7f080042
			public const int menu_favorites = 2131230786;
			
			// aapt resource value: 0x7f080043
			public const int menu_start_test = 2131230787;
			
			// aapt resource value: 0x7f08001c
			public const int scrollViewTranslateResultsDefs = 2131230748;
			
			// aapt resource value: 0x7f080045
			public const int selectCountWords = 2131230789;
			
			// aapt resource value: 0x7f080044
			public const int selectTestLevel = 2131230788;
			
			// aapt resource value: 0x7f08002d
			public const int tableLayoutAnswers = 2131230765;
			
			// aapt resource value: 0x7f080046
			public const int testSelectWords = 2131230790;
			
			// aapt resource value: 0x7f08002c
			public const int textOriginalWord = 2131230764;
			
			// aapt resource value: 0x7f08001a
			public const int textSourceString = 2131230746;
			
			// aapt resource value: 0x7f080010
			public const int text_headline = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int view_header = 2131230739;
			
			// aapt resource value: 0x7f080017
			public const int web_update_details = 2131230743;
			
			// aapt resource value: 0x7f080007
			public const int wrapper_attachments = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int wrapper_feedback = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int wrapper_feedback_scroll = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int wrapper_messages = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int wrapper_messages_buttons = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_expiry_info = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_feedback = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_update = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Dictionary = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Favorites = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FavoritesSectionListHeader = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FavoritesSectionListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int fragment_update = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SelectTestLevel = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Settings = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TestSelectWords = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int TranslateResultHeader = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int TranslateResultVariant = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int view_feedback_message = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu_DictionaryScreen = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int menu_FavoritesScreen = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int menu_SelectTestLevelScreen = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int menu_TestSelectWordsScreen = 2131165187;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040044
			public const int ApplicationName = 2130968644;
			
			// aapt resource value: 0x7f040043
			public const int Hello = 2130968643;
			
			// aapt resource value: 0x7f04005c
			public const int act_autochangedestination = 2130968668;
			
			// aapt resource value: 0x7f040058
			public const int act_favorites_caption = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int act_selectcountwords_caption = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int act_testselectwords_caption = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int act_trytoaddfavorites = 2130968667;
			
			// aapt resource value: 0x7f040045
			public const int app_name = 2130968645;
			
			// aapt resource value: 0x7f040057
			public const int caption_btn_continue = 2130968663;
			
			// aapt resource value: 0x7f040055
			public const int caption_btn_favorites = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int caption_btn_testing = 2130968662;
			
			// aapt resource value: 0x7f040054
			public const int caption_btn_translate_destination = 2130968660;
			
			// aapt resource value: 0x7f040053
			public const int caption_enter_text_for_translate = 2130968659;
			
			// aapt resource value: 0x7f040052
			public const int caption_translate_destination = 2130968658;
			
			// aapt resource value: 0x7f040000
			public const int hockeyapp_crash_dialog_app_name_fallback = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int hockeyapp_crash_dialog_message = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int hockeyapp_crash_dialog_negative_button = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int hockeyapp_crash_dialog_neutral_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int hockeyapp_crash_dialog_positive_button = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int hockeyapp_crash_dialog_title = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int hockeyapp_dialog_error_message = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hockeyapp_dialog_error_title = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int hockeyapp_dialog_negative_button = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int hockeyapp_dialog_positive_button = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int hockeyapp_download_failed_dialog_message = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int hockeyapp_download_failed_dialog_negative_button = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int hockeyapp_download_failed_dialog_positive_button = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int hockeyapp_download_failed_dialog_title = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int hockeyapp_error_no_network_message = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int hockeyapp_expiry_info_text = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int hockeyapp_expiry_info_title = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int hockeyapp_feedback_attach_file = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int hockeyapp_feedback_attach_picture = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int hockeyapp_feedback_attachment_button_text = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int hockeyapp_feedback_attachment_error = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int hockeyapp_feedback_attachment_loading = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int hockeyapp_feedback_email_hint = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int hockeyapp_feedback_failed_text = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int hockeyapp_feedback_failed_title = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int hockeyapp_feedback_generic_error = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int hockeyapp_feedback_last_updated_text = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int hockeyapp_feedback_max_attachments_allowed = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int hockeyapp_feedback_message_hint = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int hockeyapp_feedback_name_hint = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int hockeyapp_feedback_refresh_button_text = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int hockeyapp_feedback_response_button_text = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int hockeyapp_feedback_select_file = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int hockeyapp_feedback_select_picture = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int hockeyapp_feedback_send_button_text = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int hockeyapp_feedback_send_generic_error = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int hockeyapp_feedback_send_network_error = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int hockeyapp_feedback_subject_hint = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int hockeyapp_feedback_title = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int hockeyapp_feedback_validate_email_empty = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int hockeyapp_feedback_validate_email_error = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int hockeyapp_feedback_validate_name_error = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int hockeyapp_feedback_validate_subject_error = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int hockeyapp_feedback_validate_text_error = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int hockeyapp_login_email_hint = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int hockeyapp_login_headline_text = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int hockeyapp_login_login_button_text = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int hockeyapp_login_missing_credentials_toast = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int hockeyapp_login_password_hint = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int hockeyapp_paint_dialog_message = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int hockeyapp_paint_dialog_negative_button = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int hockeyapp_paint_dialog_neutral_button = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int hockeyapp_paint_dialog_positive_button = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int hockeyapp_paint_indicator_toast = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int hockeyapp_paint_menu_clear = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int hockeyapp_paint_menu_save = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int hockeyapp_paint_menu_undo = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int hockeyapp_permission_dialog_negative_button = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int hockeyapp_permission_dialog_positive_button = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int hockeyapp_permission_update_message = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int hockeyapp_permission_update_title = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int hockeyapp_update_button = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int hockeyapp_update_dialog_message = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int hockeyapp_update_dialog_negative_button = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int hockeyapp_update_dialog_positive_button = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int hockeyapp_update_dialog_title = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int hockeyapp_update_mandatory_toast = 2130968642;
			
			// aapt resource value: 0x7f04004d
			public const int msg_cancel = 2130968653;
			
			// aapt resource value: 0x7f040050
			public const int msg_error_try_again = 2130968656;
			
			// aapt resource value: 0x7f04004e
			public const int msg_final_test = 2130968654;
			
			// aapt resource value: 0x7f04004c
			public const int msg_ok = 2130968652;
			
			// aapt resource value: 0x7f04004b
			public const int msg_repeat = 2130968651;
			
			// aapt resource value: 0x7f040047
			public const int msg_string_added_to_fav = 2130968647;
			
			// aapt resource value: 0x7f040046
			public const int msg_string_deleted_from_fav = 2130968646;
			
			// aapt resource value: 0x7f04004f
			public const int msg_test_select_count_word = 2130968655;
			
			// aapt resource value: 0x7f040049
			public const int msg_tests_repeatOrClose = 2130968649;
			
			// aapt resource value: 0x7f040051
			public const int msg_testselectwords_select = 2130968657;
			
			// aapt resource value: 0x7f040048
			public const int msg_unknown_expression = 2130968648;
			
			// aapt resource value: 0x7f04004a
			public const int msg_warning = 2130968650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050009
			public const int FavoritesDeletedItemTextView = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int HockeyApp_ButtonStyle = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int HockeyApp_EditTextStyle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int HockeyApp_SingleLineInputStyle = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int MainButton = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int Mono_Android_Theme_Splash = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int MyActionBar = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int MyTheme = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int MyTheme_Splash = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int TestSelectWordsButtonSubmit = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int VariantHeaderTextView = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int VariantItemTextView = 2131034119;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
