#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TranslateHelper.Droid.Resource", IsApplication=true)]

namespace TranslateHelper.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int ab_white = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int black = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int blue_background = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int grey = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int lightgrey = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int red_background = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int transparent = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int white = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int white1 = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int book = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int change = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int favorites = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int list = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int right = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rigth2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int settings = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001b
			public const int FavoritesStatePic = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int IndexTextView = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int PosTextView = 2131165210;
			
			// aapt resource value: 0x7f07000e
			public const int SourceTextView1 = 2131165198;
			
			// aapt resource value: 0x7f070019
			public const int TranscriptionTextView = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int TranslatedTextView = 2131165208;
			
			// aapt resource value: 0x7f07000f
			public const int TranslatedTextView1 = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int buttonDictionary = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int buttonFavorites = 2131165203;
			
			// aapt resource value: 0x7f070007
			public const int buttonNew = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int buttonNewBottom = 2131165194;
			
			// aapt resource value: 0x7f070016
			public const int buttonSettings = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int buttonTesting = 2131165205;
			
			// aapt resource value: 0x7f070008
			public const int buttonTranslate = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int changeLanButton = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int dictList = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int favoritesLayout = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int listChangeLang = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int listFavoritesListView = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int listInputString = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int listResultListView = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int mainLayout = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int mainList = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int mainList1 = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int mainList2 = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int textDestinationLang = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int textSourceLang = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int textSourceString = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dictionary = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Favorites = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FavoritesItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Settings = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TranslateResultItem = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MainButton = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
